# Generated by Django 6.0.7 on 2026-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(help_text="e.g., 'July 2024'", max_length=50)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('hover_glow', models.CharField(default='#7B61FF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=10)),
                ('end_year', models.CharField(default='Present', max_length=10)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('start_date', models.CharField(help_text="e.g., 'June 2024'", max_length=50)),
                ('end_date', models.CharField(help_text="e.g., 'August 2024' or 'Present'", max_length=50)),
                ('achievements', models.TextField(help_text='Line-separated achievements or JSON list')),
                ('responsibilities', models.TextField(help_text='Line-separated responsibilities or JSON list')),
                ('is_current', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('order', models.IntegerField(default=0, help_text='Ordering index')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='S Sreesh', max_length=100)),
                ('title', models.CharField(default='Software Developer | Python Developer', max_length=200)),
                ('location', models.CharField(default='Kerala, India', max_length=100)),
                ('email', models.EmailField(default='ssreesh45@gmail.com', max_length=254)),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/s-sreesh')),
                ('github', models.URLField(default='https://github.com/Sreesh-S')),
                ('portfolio_url', models.URLField(default='https://sreesh-portfolio.vercel.app/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Short summary for listing card')),
                ('long_description', models.TextField(help_text='Detailed description (supports markdown or HTML)')),
                ('image', models.ImageField(upload_to='projects/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma-separated tech names, e.g., Python, Django, ML', max_length=300)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('case_study_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('features', models.TextField(help_text='JSON list of core features or line-separated text')),
                ('challenges', models.TextField(blank=True, null=True)),
                ('architecture_diagram', models.ImageField(blank=True, null=True, upload_to='projects/architecture/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'ordering': ['-download_time'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web', 'Web Development'), ('Machine Learning', 'Machine Learning & AI'), ('Data', 'Data Analytics & Visualisation'), ('Database', 'Databases'), ('Tools', 'Tools & Devops')], max_length=30)),
                ('proficiency', models.IntegerField(help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(help_text="FontAwesome class e.g., 'fa-brands fa-python'", max_length=100)),
                ('hover_glow', models.CharField(default='#00F5FF', help_text='Hex color code for glow, e.g., #00F5FF', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="e.g., 'fa-brands fa-github'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visit_time'],
            },
        ),
    ]
