# Generated by Django 6.0.7 on 2026-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(default='English, Malayalam, Hindi', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+91 81294 10562', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='soft_skills',
            field=models.CharField(default='Problem Solving, Analytical Thinking, Team Collaboration, Time Management, Continuous Learning', max_length=300),
        ),
    ]
