# Generated by Django 6.0.7 on 2026-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_languages_profile_phone_profile_soft_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
