# Generated by Django 6.0.7 on 2026-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resumefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_heading',
            field=models.CharField(default='Developing Next-Gen Intelligent Stacks', max_length=200),
        ),
    ]
